name: Infra Apply

on:
  push:
    branches: [main]
    paths:
      - 'infra/**'

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Apply infrastructure"
